- dates: 4.1.2019 - 31.5.2019
  times:
    - time: ma 19:00-20:30
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a>
    - time: ke 16:00-17:30
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a>
    - time: to 19:30-21:00
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a> (10.1. asti, sen jälkeen alkeiskurssi)
    - time: pe 18:30-20:00
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a>
    - time: su 9:30-11:00
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a> (vapaavuoro)