- dates: 1.9.2019 – 31.12.2019
  times:
    - time: ma 18:30 – 20:00
      location: &TOOLO <a href="https://goo.gl/maps/Hcs6GgR9x8ebmiZp9" target="_blank">Töölön ala-aste</a> 
    - time: ti 19:00 – 20:30 (10.12. asti)
      location: *TOOLO
    - time: to 18:45 – 20:15
      location: &PORTSU <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a>
    - time: la 13:00 – 14:30 (vapaavuoro, 28.12. asti)
      location: *TOOLO
    - time: su 10:00 – 11:30 (vapaavuoro)
      location: *PORTSU
- dates: 1.6.2019 - 31.8.2019
  times:
    - time: ma 18:00-19:30 (<b>vain 3.6.-15.7.</b>)
      location: <a href="https://goo.gl/maps/2Ajrquq2gPmHCHQz8" target="_blank">Grundskolan Norsen</a>
    - time: to 19:35-21:05 (6.6.-29.8.)
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a>