- dates: 1.6.2019 - 31.8.2019
  times:
    - time: ma 18:00-19:30 (<b>vain 3.6.-15.7.</b>)
      location: <a href="https://goo.gl/maps/2Ajrquq2gPmHCHQz8" target="_blank">Grundskolan Norsen</a>
    - time: to 19:35-21:05 (6.6.-29.8.)
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a>
- dates: 4.1.2019 - 31.5.2019
  times:
    - time: ma 19:00-20:30
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a>
    - time: ke 16:00-17:30
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a>
    - time: to 19:30-21:00
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a> (alkeiskurssi)
    - time: pe 18:30-20:00
      location: <a href="https://goo.gl/maps/t21PcHXy8ky" target="_blank">Porthania</a>
    - time: la 14:00-15:30
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a> (vapaavuoro)
    - time: su 9:30-11:00
      location: <a href="https://goo.gl/maps/dxdFtMgjEEL2" target="_blank">Unidojo</a> (vapaavuoro)